# Generated by Django 4.2.7 on 2025-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        # Use SQL with IF EXISTS to avoid errors when indexes/columns are absent
        migrations.RunSQL(
            sql=(
                "DROP INDEX IF EXISTS incidents_status_0ce7fe_idx;\n"
                "DROP INDEX IF EXISTS incidents_type_b7ff70_idx;\n"
                "DROP INDEX IF EXISTS incidents_reporte_aca25f_idx;\n"
                "DROP INDEX IF EXISTS incidents_inciden_01baf6_idx;\n"
                "ALTER TABLE incidents DROP COLUMN IF EXISTS idempotency_key;\n"
                "ALTER TABLE incidents DROP COLUMN IF EXISTS incident_day;\n"
                "ALTER TABLE incidents DROP COLUMN IF EXISTS photos_count;\n"
                "ALTER TABLE incidents DROP COLUMN IF EXISTS title;\n"
                "ALTER TABLE incidents DROP COLUMN IF EXISTS type;"
            ),
            reverse_sql=(
                # No-op reverse; recreating dropped indexes/columns intentionally omitted
                "SELECT 1;"
            ),
        ),
        # Add columns only if they don't exist
        migrations.RunSQL(
            sql=(
                "DO $$ BEGIN "
                "IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='incidents' AND column_name='incident_type') THEN "
                "ALTER TABLE incidents ADD COLUMN incident_type VARCHAR(30) DEFAULT 'punto_acopio' NOT NULL; "
                "END IF; "
                "END $$;\n"
                "DO $$ BEGIN "
                "IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='incidents' AND column_name='photo_url') THEN "
                "ALTER TABLE incidents ADD COLUMN photo_url TEXT NULL; "
                "END IF; "
                "END $$;"
            ),
            reverse_sql="SELECT 1;",
        ),
    ]
