# Generated by Django 4.2.7 on 2025-12-07 20:57

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('zone_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('priority', models.IntegerField(default=1, help_text='1=Baja, 5=Muy alta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='daily', max_length=10)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('assigned_team_size', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('maintenance', 'En mantenimiento')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona de Limpieza',
                'verbose_name_plural': 'Zonas de Limpieza',
                'db_table': 'cleaning_zones',
                'ordering': ['-priority', 'zone_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=200)),
                ('route_geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('waypoints', models.JSONField(help_text='Array de puntos con lat/lon')),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('optimization_algorithm', models.CharField(default='osrm', help_text='Algoritmo usado para optimización', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('archived', 'Archivada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.cleaningzone')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waypoint_order', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('waypoint_type', models.CharField(blank=True, choices=[('start', 'Inicio'), ('collection', 'Recolección'), ('disposal', 'Disposición'), ('end', 'Fin')], max_length=20, null=True)),
                ('estimated_service_minutes', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_waypoints', to='routes.route')),
            ],
            options={
                'verbose_name': 'Punto de Ruta',
                'verbose_name_plural': 'Puntos de Ruta',
                'db_table': 'route_waypoints',
                'ordering': ['route', 'waypoint_order'],
                'unique_together': {('route', 'waypoint_order')},
            },
        ),
    ]
