# Generated by Django 4.2.7 on 2025-12-07 20:57

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0002_remove_incident_incidents_status_0ce7fe_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Muy Baja'), (2, 'Baja'), (3, 'Normal'), (4, 'Alta'), (5, 'Urgente')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicación específica de la tarea', null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('scheduled_date', models.DateField(blank=True, help_text='Fecha programada para realizar la tarea', null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, help_text='Hora de inicio programada', null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, help_text='Hora de finalización programada', null=True)),
                ('estimated_duration', models.IntegerField(default=30, help_text='Duración estimada en minutos')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('team_size', models.IntegerField(default=1, help_text='Número de trabajadores necesarios', validators=[django.core.validators.MinValueValidator(1)])),
                ('equipment_needed', models.JSONField(blank=True, default=list, help_text='Lista de equipamiento necesario')),
                ('materials_needed', models.JSONField(blank=True, default=list, help_text='Lista de materiales necesarios')),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('checkpoints_completed', models.IntegerField(default=0)),
                ('checkpoints_total', models.IntegerField(default=0)),
                ('result_notes', models.TextField(blank=True)),
                ('result_photos', models.JSONField(blank=True, default=list, help_text='URLs de fotos del resultado')),
                ('waste_collected_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de residuos recolectados en kg', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, help_text='Incidencia que generó esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='incidents.incident')),
                ('route', models.ForeignKey(blank=True, help_text='Ruta asociada a esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='routes.route')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tasks',
                'ordering': ['-priority', 'scheduled_date', 'scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_order', models.IntegerField(help_text='Orden del checkpoint en la secuencia', validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicación del punto de control', null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Checkpoint de Tarea',
                'verbose_name_plural': 'Checkpoints de Tareas',
                'db_table': 'task_checkpoints',
                'ordering': ['task', 'checkpoint_order'],
                'indexes': [models.Index(fields=['task', 'is_completed'], name='task_checkp_task_id_b1fef7_idx'), models.Index(fields=['completed_at'], name='task_checkp_complet_0834d4_idx')],
                'unique_together': {('task', 'checkpoint_order')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('assigned', 'Asignada'), ('reassigned', 'Reasignada'), ('unassigned', 'Desasignada'), ('started', 'Iniciada'), ('paused', 'Pausada'), ('resumed', 'Reanudada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_actions', to=settings.AUTH_USER_MODEL)),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'verbose_name_plural': 'Historial de Asignaciones',
                'db_table': 'task_assignments_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['task', '-timestamp'], name='task_assign_task_id_84b4bc_idx'), models.Index(fields=['performed_by', '-timestamp'], name='task_assign_perform_e4188f_idx'), models.Index(fields=['action', '-timestamp'], name='task_assign_action_b68851_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'scheduled_date'], name='tasks_status_406ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_assigne_801c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'status'], name='tasks_priorit_2b45be_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_created_db4e37_idx'),
        ),
    ]
