# Generated by Django 4.2.7 on 2025-12-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes.statistics',
                'ordering': ['-date'],
                'unique_together': {('stat_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('daily', 'Reporte Diario'), ('weekly', 'Reporte Semanal'), ('monthly', 'Reporte Mensual'), ('custom', 'Reporte Personalizado'), ('tasks', 'Reporte de Tareas'), ('incidents', 'Reporte de Incidencias'), ('routes', 'Reporte de Rutas'), ('performance', 'Reporte de Rendimiento')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_path', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('file_url', models.URLField(blank=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='reports_report__af00dc_idx'), models.Index(fields=['generated_by', '-created_at'], name='reports_generat_4f8043_idx')],
            },
        ),
    ]
